[project]
name = "orion"
version = "0.3.0"
description = "My very own coding agent"
authors = [{ name = "Vraj Patel", email = "vrajpat3ll@gmail.com" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.1",
    "ddgs>=9.10.0",
    "openai>=2.15.0",
    "platformdirs>=4.5.1",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "rich>=14.2.0",
    "tavily-python>=0.7.20",
    "tiktoken>=0.12.0",
    "tomli>=2.4.0",
]

[dependency-groups]
dev = [
    "orion",
    "ruff>=0.15.4",
    "taskipy>=1.14.1",
]

[tool.taskipy.tasks]
check = "ruff check"
fmt = "ruff format"
lint = "task fmt && task check"

[tool.uv.sources]
orion = { workspace = true }

[project.scripts]
orion = "orion.main:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
